name: HTML Check

on:
  push:
  workflow_dispatch:


jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      HTML5_ACTION_DEBUG: true
    steps:

    - uses: actions/checkout@v3

    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action-experimental@master
      with:
        root: .
        log_level: DEBUG