name: HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find File Path
      run: pwd test.html
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: test.html