name: HTML Check

on:
  push:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Checks HTML5
      id: action
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: /tmp/missing
        log_level: DEBUG
      env:
        HTML5_ACTION_DEBUG: true

    - name: Echo Result code
      run: |
        echo ${{ steps.action.outputs.result }}